src/Entity/Message.php
<?php

namespace App\Entity;

use App\Repository\MessageRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: MessageRepository::class)]
class Message
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private $id;

    #[ORM\Column(type: 'string', length: 255)]
    private $titre;

    #[ORM\Column(type: 'text')]
    private $contenu;

    #[ORM\Column(type: 'datetime')]
    private $date_envoi;

    #[ORM\ManyToOne(targetEntity: User::class, inversedBy: 'messages')]
    #[ORM\JoinColumn(nullable: false)]
    private $destinataire;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitre(): ?string
    {
        return $this->titre;
    }

    public function setTitre(string $titre): self
    {
        $this->titre = $titre;

        return $this;
    }

    public function getContenu(): ?string
    {
        return $this->contenu;
    }

    public function setContenu(string $contenu): self
    {
        $this->contenu = $contenu;

        return $this;
    }

    public function getDateEnvoi(): ?\DateTimeInterface
    {
        return $this->date_envoi;
    }

    public function setDateEnvoi(\DateTimeInterface $date_envoi): self
    {
        $this->date_envoi = $date_envoi;

        return $this;
    }

    public function getDestinataire(): ?User
    {
        return $this->destinataire;
    }

    public function setDestinataire(?User $destinataire): self
    {
        $this->destinataire = $destinataire;

        return $this;
    }
}

src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: UserRepository::class)]
class User
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private $id;

    #[ORM\Column(type: 'string', length: 100)]
    private $nom;

    #[ORM\Column(type: 'string', length: 100)]
    private $prenom;

    #[ORM\Column(type: 'string', length: 255)]
    private $adresse;

    #[ORM\Column(type: 'string', length: 100)]
    private $ville;

    #[ORM\Column(type: 'string', length: 10)]
    private $cp;

    #[ORM\Column(type: 'string', length: 100)]
    private $email;

    #[ORM\Column(type: 'string', length: 20, nullable: true)]
    private $tel;

    #[ORM\Column(type: 'float')]
    private $salaire;

    #[ORM\Column(type: 'string', length: 100, nullable: true)]
    private $service;

    #[ORM\Column(type: 'datetime', nullable: true)]
    private $date_naissance;

    #[ORM\OneToMany(mappedBy: 'destinataire', targetEntity: Message::class)]
    private $messages;

    public function __construct()
    {
        $this->messages = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): self
    {
        $this->nom = $nom;

        return $this;
    }

    public function getPrenom(): ?string
    {
        return $this->prenom;
    }

    public function setPrenom(string $prenom): self
    {
        $this->prenom = $prenom;

        return $this;
    }

    public function getAdresse(): ?string
    {
        return $this->adresse;
    }

    public function setAdresse(string $adresse): self
    {
        $this->adresse = $adresse;

        return $this;
    }

    public function getVille(): ?string
    {
        return $this->ville;
    }

    public function setVille(string $ville): self
    {
        $this->ville = $ville;

        return $this;
    }

    public function getCp(): ?string
    {
        return $this->cp;
    }

    public function setCp(string $cp): self
    {
        $this->cp = $cp;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    public function getTel(): ?string
    {
        return $this->tel;
    }

    public function setTel(?string $tel): self
    {
        $this->tel = $tel;

        return $this;
    }

    public function getSalaire(): ?float
    {
        return $this->salaire;
    }

    public function setSalaire(float $salaire): self
    {
        $this->salaire = $salaire;

        return $this;
    }

    public function getService(): ?string
    {
        return $this->service;
    }

    public function setService(?string $service): self
    {
        $this->service = $service;

        return $this;
    }

    public function getDateNaissance(): ?\DateTimeInterface
    {
        return $this->date_naissance;
    }

    public function setDateNaissance(?\DateTimeInterface $date_naissance): self
    {
        $this->date_naissance = $date_naissance;

        return $this;
    }

    /**
     * @return Collection<int, Message>
     */
    public function getMessages(): Collection
    {
        return $this->messages;
    }

    public function addMessage(Message $message): self
    {
        if (!$this->messages->contains($message)) {
            $this->messages[] = $message;
            $message->setDestinataire($this);
        }

        return $this;
    }

    public function removeMessage(Message $message): self
    {
        if ($this->messages->removeElement($message)) {
            // set the owning side to null (unless already changed)
            if ($message->getDestinataire() === $this) {
                $message->setDestinataire(null);
            }
        }

        return $this;
    }
    // public function __toString()
    // {
    //     return $this->nom . $this->prenom;
    // }
}

src/Controller/UserController.php
<?php

namespace App\Controller;

use App\Entity\User;
use App\Form\AjouterUserType;
use App\Repository\UserRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class UserController extends AbstractController
{
    // Affiche la liste des utilisateurs
    #[Route('/user', name: 'app_user')]
    public function index(Request $request, UserRepository $userRepository): Response
    {
        // instancier un objet User
        $user = new User();

        // création d'un formulaire et lier avec l'objet User
        $form = $this->createForm(AjouterUserType::class, $user);

        // je mets mon formulaire à l'écoute des requetes qui passe dans l'URL
        $form->handleRequest($request);

        // verifier si le formulaire est soumis et valide
        if ($form->isSubmitted() && $form->isValid()) {
            $userRepository->add($user);

            return $this->redirectToRoute('app_user');
        }

        return $this->render('user/user.html.twig', [
            "liste_users" => $userRepository->findAll(),
            "form" => $form->createView()
        ]);
    }

    // Afficher un utilisateur
    #[Route('/profil-user/{id}', name: 'app_profil_user')]
    public function getOneUser($id, UserRepository $userRepository): Response
    {
        $user = $userRepository->find($id);
        return $this->render('user/show_user.html.twig', [
            "users" => $user,
            "messages" => $user->getMessages(),
        ]);
    }

    // Ajouter un utilisateur
    #[Route('/ajouter-user', name: 'app_add_user')]
    public function addUser(Request $request, UserRepository $userRepository, EntityManagerInterface $manager): Response
    {
        // instancier un objet User
        $user = new User();

        // création d'un formulaire et lier avec l'objet User
        $form = $this->createForm(AjouterUserType::class, $user);

        // je mets mon formulaire à l'écoute des requetes qui passe dans l'URL
        $form->handleRequest($request);

        // verifier si le formulaire est soumis et valide
        if ($form->isSubmitted() && $form->isValid()) {
            $userRepository->add($user);
            /* $manager->persist($user);
            $manager->flush(); */

            return $this->redirectToRoute('app_user');
        }

        return $this->render('user/add_user.html.twig', [
            "form" => $form->createView(),
        ]);
    }

    // Supprimer un utilisateur
    #[Route('/delete-user/{id}', name: 'app_remove_user')]
    public function deleteUser($id, UserRepository $userRepository): Response
    {
        $user = $userRepository->find($id);

        if ($user) {
            $userRepository->remove($user);

            return $this->redirectToRoute('app_user');
        }
    }

    // Editer un utilisateur
    #[Route('/modifier-user/{id}', name: 'app_edit_user')]
    public function editUser(
        $id,
        Request $request,
        UserRepository $userRepository,
    ): Response {
        // instancier un objet User
        $user = $userRepository->find($id);

        // création d'un formulaire et lier avec l'objet User
        $form = $this->createForm(AjouterUserType::class, $user);

        // je mets mon formulaire à l'écoute des requetes qui passe dans l'URL
        $form->handleRequest($request);

        // verifier si le formulaire est soumis et valide
        if ($form->isSubmitted() && $form->isValid()) {
            $userRepository->add($user);

            return $this->redirectToRoute('app_user');
        }

        return $this->render('user/edit_user.html.twig', [
            "form" => $form->createView(),
        ]);
    }
}

templates/user/add_user.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello UserController!{% endblock %}

{% block body %}
<div class="container">
    <div class="col-md-6 mx-auto my-4">
    <h1 class="text-center text-muted my-3" >Ajouter un user</h1>
    {{ form_start(form) }}
        <div class="row">
            <div class="col-6">
                {{ form_row(form.nom) }}
            </div>
            <div class="col-6">
                {{ form_row(form.prenom) }}
            </div>
        </div>

        <div class="row">
            <div class="col-6">{{ form_row(form.email) }}</div>
            <div class="col-6">{{ form_row(form.tel) }}</div>
        </div>

        <div class="row">
            <div class="col">
                {{ form_row(form.adresse) }}
            </div>
        </div>

        <div class="row">
            <div class="col-8">
                {{ form_row(form.ville) }}
            </div>
            <div class="col-4">
                {{ form_row(form.cp) }}
            </div>
        </div>

        <div class="row">
            <div class="col-6">{{ form_row(form.salaire) }}</div>
            <div class="col-6">{{ form_row(form.service) }}</div>
        </div>

         <div class="row">
            <div class="col">
                {{ form_row(form.date_naissance) }}
            </div>
        </div>
    <input type="submit" value="ajouter" class='btn btn-dark' >
    {{ form_end(form) }}
    </div>
</div>

{% endblock %}

templates/user/edit_user.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello UserController!{% endblock %}

{% block body %}
<div class="container">
    <div class="col-md-6 mx-auto my-4">
    <h1 class="text-center text-muted my-3" >Editer un user</h1>
    {{ form_start(form) }}
        <div class="row">
            <div class="col-6">
                {{ form_row(form.nom) }}
            </div>
            <div class="col-6">
                {{ form_row(form.prenom) }}
            </div>
        </div>

        <div class="row">
            <div class="col-6">{{ form_row(form.email) }}</div>
            <div class="col-6">{{ form_row(form.tel) }}</div>
        </div>

        <div class="row">
            <div class="col">
                {{ form_row(form.adresse) }}
            </div>
        </div>

        <div class="row">
            <div class="col-8">
                {{ form_row(form.ville) }}
            </div>
            <div class="col-4">
                {{ form_row(form.cp) }}
            </div>
        </div>

        <div class="row">
            <div class="col-6">{{ form_row(form.salaire) }}</div>
            <div class="col-6">{{ form_row(form.service) }}</div>
        </div>

         <div class="row">
            <div class="col">
                {{ form_row(form.date_naissance) }}
            </div>
        </div>
    <input type="submit" value="ajouter" class='btn btn-dark' >
    {{ form_end(form) }}
    </div>
</div>

{% endblock %}

templates/user/show_user.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello UserController!{% endblock %}

{% block body %}
	<div class="container text-center">
		<div class="row">
			<div class="col-sm-12">
				<h1>Profil utilisateur</h1>
				<div class="row">
					<div class="col-sm-12">
						<div class="card">
							<div class="card-body">
								<h5 class="card-title">{{ user.prenom }}
									{{ user.nom }}</h5>
								<p class="card-text">Date de naissance :
									{{ user.dateNaissance|date("Y/m/d") }}</p>
								<p class="card-text">
									Adresse :
									{{ user.adresse }}</p>
								<p class="card-text">Ville :
									{{ user.ville }}</p>
								<p class="card-text">Code postal :
									{{ user.cp }}</p>
								<p class="card-text">Email :
									{{ user.email }}</p>
								<p class="card-text">Téléphone :
									{{ user.tel }}</p>
								<p class="card-text">Service :
									{{ user.service }}</p>
								<p class="card-text">Salaire :
									{{ user.salaire }}€</p>
								<a href="{{ path('app_edit_user', { 'id': user.getId() }) }}" class="btn btn-primary">Modifier</a>

							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
	<div class="container">
	<h2 class="my-3">Listes des messages</h2>
		<table class="table">
			<thead>
				<tr>
					<th scope="col">#</th>
					<th scope="col">titre</th>
					<th scope="col">Contenu</th>
					<th scope="col">Date de reception</th>
                    <th scope="col">Actions</th>
				</tr>
			</thead>
			<tbody>
				{% for msg in messages %}
					<tr>
						<td>{{ msg.id }}</td>
						<td>{{ msg.titre }}</td>
						<td>{{ msg.contenu }}</td>
						<td>{{ msg.dateEnvoi ? msg.dateEnvoi|date('Y-m-d H:i:s') }}</td>
						<td class='d-flex align-items-center' >
                            <a onclick="return confirm('Are you sure?')" href="{{ path('app_message_delete', { 'id': msg.getId() }) }}" class='btn btn-sm btn-danger' title='supprimer utilisateur'><i class="fa-solid fa-trash-can"></i></a>
                        </td>
					</tr>
				{% endfor %}
			</tbody>
		</table>
	</div>
{% endblock %}

templates/user/user.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello UserController!{% endblock %}

{% block body %}

<div class="container-fluid">
    {# <div>
        <a href="{{ path('app_add_user') }}" class='btn btn-primary my-3' >Ajouter user</a>
    </div> #}
    <div class="row justify-content-between g-5">
        <div class="overflow-scroll">
            <h2 class="text-center text-muted my-3" >Liste des users</h2>
            <table class="table">
                <thead>
                    <tr>
                    <th scope="col">#</th>
                    <th scope="col">Nom</th>
                    <th scope="col">Prenom</th>
                    <th scope="col">Adresse</th>
                    <th scope="col">Ville</th>
                    <th scope="col">Code Postal</th>
                    <th scope="col">Email</th>
                    <th scope="col">Telephone</th>
                    <th scope="col">Salaire</th>
                    <th scope="col">Service</th>
                    <th scope="col">Date de naissance</th>
                    <th scope="col">Actions</th>
                    </tr>
                </thead>
                <tbody>
                {% for user in liste_users %}
                    <tr>
                        <th>{{ user.getId}}</th>
                        <td>{{ user.getNom() }}</td>
                        <td>{{ user.getPrenom() }}</td>
                        <td>{{ user.getAdresse() }}</td>
                        <td>{{ user.getVille() }}</td>
                        <td>{{ user.getCp() }}</td>
                        <td>{{ user.getEmail() }}</td>
                        <td>{{ user.getTel() }}</td>
                        <td>{{ user.getSalaire() }}</td>
                        <td>{{ user.getService() }}</td>
                        <td>{{ user.getDateNaissance|date("m/d/Y") }}</td>
                        {# Below is how to add parameter to a href link #}
                        <td class='d-flex align-items-center' >
                            <a href="{{ path('app_detail_user', { 'id': user.getId() }) }}" class='btn btn-sm btn-dark' title='voir details'><i class="fa-solid fa-circle-info"></i></a>
                            |
                            <a href="{{ path('app_message_new', { 'id': user.getId() }) }}" class='btn btn-sm btn-success' title='envoyez un message'><i class="fa-solid fa-message"></i></a>
                            |
                            <a href="{{ path('app_edit_user', { 'id': user.getId() }) }}" class='btn btn-sm btn-primary' title='editer le profil'><i class="fa-solid fa-pen"></i></a>
                            | 
                            <a onclick="return confirm('Are you sure?')" href="{{ path('app_remove_user', { 'id': user.getId() }) }}" class='btn btn-sm btn-danger' title='supprimer utilisateur'><i class="fa-solid fa-trash-can"></i></a>
                        </td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
        <hr>
        <div class="row">
            <div class='col-6 mx-auto mb-5'>
                <h2 class="text-center text-muted my-3" >Ajouter un user</h2>
                {{ form_start(form) }}
                <div class="row">
                    <div class="col-6">
                        {{ form_row(form.nom) }}
                    </div>
                    <div class="col-6">
                        {{ form_row(form.prenom) }}
                    </div>
                </div>

                <div class="row">
                    <div class="col-6">{{ form_row(form.email) }}</div>
                    <div class="col-6">{{ form_row(form.tel) }}</div>
                </div>

                <div class="row">
                    <div class="col">
                        {{ form_row(form.adresse) }}
                    </div>
                </div>

                <div class="row">
                    <div class="col-8">
                        {{ form_row(form.ville) }}
                    </div>
                    <div class="col-4">
                        {{ form_row(form.cp) }}
                    </div>
                </div>

                <div class="row">
                    <div class="col-6">{{ form_row(form.salaire) }}</div>
                    <div class="col-6">{{ form_row(form.service) }}</div>
                </div>

                <div class="row">
                    <div class="col">
                        {{ form_row(form.date_naissance) }}
                    </div>
                </div>
                <input type="submit" value="ajouter" class='btn btn-dark' >
                {{ form_end(form) }}
            </div>
        </div>
    </div>
</div>

{% endblock %}